version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:7.4.0-v3
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis-stack.conf:/redis-stack.conf

volumes:
  postgres_data:
  redis_data: